# -*- coding: utf-8 -*-
"""colab_student_mark_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VehS-5-Mbe1VwKFy20ctOn81cTIsyc-i

# Student Mark Analysis
This notebook analyzes student marks using Python and Pandas.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv('student_marks.csv')
df.head()

# Display basic information
print(df.info())
print('\nAverage Marks:')
print(df[['Maths','Science','English']].mean())

# Top performing student
top_student = df.loc[df['Total'].idxmax()]
print('Top Performing Student:')
print(top_student)

# Plot average marks subject-wise
subjects = ['Maths', 'Science', 'English']
avg_marks = df[subjects].mean()

plt.figure(figsize=(6,4))
plt.bar(subjects, avg_marks)
plt.xlabel('Subjects')
plt.ylabel('Average Marks')
plt.title('Average Marks by Subject')
plt.show()